### ISSUE TITLE
get current selectedButton()

### ISSUE THREAD

**Issue by dneykov** [shamasshahid/SSRadioButtonsController#1]
I'm not able to get current selected button. I'm trying to get it in IBAction on save button.
Any suggestions? Thanks

**Comment by shamasshahid** [comment]
@dneykov  Are you using the following snippet
`var currentButton = radioButtonController.selectedButton()`
Did you add it RadioButtonController first?

**Comment by dneykov** [comment]
this is how I'm trying to get current button:

@IBAction func saveInspection(sender: AnyObject) {
        var currentButton = radioButtonController.selectedButton()
        println(currentButton)
    }
and this is my viewDidLoad:
radioButtonController.setButtonsArray([buttonAA!,buttonA!,buttonB!,buttonC,buttonD])

for the currentButton I get always nil.
Thanks

**Comment by shamasshahid** [comment]
@dneykov Just pushed a code. It's working all right now. 
Let me know.

**Comment by dneykov** [comment]
It is working now.
Thanks.

**Comment by RMK19** [comment]
currentSelectedButton now returns nil always.
i have used a buttonOutletCollection.

radioButtonGroup.setButtonsArray(bloodGroupButton)

func didButtonGroupSelected(sender: UIButton) {
        var control = radioButtonGroup.selectedButton()
        print(control) //prints nil
    }
