### ISSUE TITLE
RadioButton with no text

### ISSUE THREAD

**Issue by 4QStudios** [shamasshahid/SSRadioButtonsController#10]
Hi, i noted that when the buttons have no text, it gets filled like this 
![img_0271](https://cloud.githubusercontent.com/assets/14880293/13009276/598fcd70-d17a-11e5-9f42-6986aac161a2.PNG)

Is there a way to just show the circle? Thanks.

**Comment by shamasshahid** [comment]
Your button type is set to System. Please change it to Custom. This will fix the issue. 

Also, when you change it to custom, you will have to set title color as well. Otherwise text will be white in color.

**Comment by 4QStudios** [comment]
thank you! it works

**Comment by emmtqg** [comment]
Cheers, thank you! It's perfect!
