### ISSUE TITLE
Radio button being filled in.....

### ISSUE THREAD

**Issue by MPikDev** [shamasshahid/SSRadioButtonsController#11]
I have a big table view with a lot of radio button all of them have different section and they all have their own radio button controllers but when i scroll from one section to the next they get selected by themselves.

![img_5909](https://cloud.githubusercontent.com/assets/11655358/13240590/a8848b84-d998-11e5-96ef-fc73045bb5ec.jpg)
![img_5910](https://cloud.githubusercontent.com/assets/11655358/13240589/a8671bbc-d998-11e5-9aa8-23590dae56c1.jpg)

**Comment by shamasshahid** [comment]
Are you still facing this issue? Can you share an example of the code where you are facing this issue?

**Comment by MPikDev** [comment]
Thank you for getting back to me, yes I still have the issue here is the link to my repository and if you run it choose some of the radio buttons then scroll up and down a couple of times, and the radio buttons will start to get selected and unselected. https://github.com/lego7man/SurveyViewController

I have been trying to isolate the problem but i have no luck. Thats why i can't just send you the code that I'm having an issue with.

**Comment by MPikDev** [comment]
I think I got it

**Comment by TEJ227** [comment]
@MPikDev, How did you solve this issue

**Comment by MPikDev** [comment]
I cant total recall (its been awhile), but the I think I made images that where linked to the radio button controller and redraw them based on the state that the radio button controller had the buttons saved

**Comment by TEJ227** [comment]
@MPikDev  nevermind, solved my issue using basic UIButton only. Thanks for the reply though
