### ISSUE TITLE
vertically align the circle radius to top

### ISSUE THREAD

**Issue by adam704a** [shamasshahid/SSRadioButtonsController#17]
![screen_shot_2016-08-15_at_10_31_44_am](https://cloud.githubusercontent.com/assets/276936/17671343/d4484688-62d3-11e6-9f65-d4e3924fc3b5.png)

**Comment by shamasshahid** [comment]
Hey Adam, sorry for not replying sooner. You can center align it by checking the property for Control Alignment in storyboard. 
<img width="258" alt="screen shot 2016-10-16 at 6 53 40 pm" src="https://cloud.githubusercontent.com/assets/1205342/19416953/ed1286b8-93d1-11e6-9ebe-176a8587bcef.png">
