### ISSUE TITLE
Unable to change textLabel background when radion selected, blue is default background Color

### ISSUE THREAD

**Issue by Mahadev77** [shamasshahid/SSRadioButtonsController#23]
Unable to change textLabel background when radio selected, blue is default background color
Please help me to sovle this problem, I want to change color different from blue color

**Comment by cristiann91** [comment]
Hi! I wasn't able to change the colour but could make the background colour transparent. Just set the button type to Custom. 
![b](https://cloud.githubusercontent.com/assets/4093683/24473325/459b2b2a-149f-11e7-8fca-c1a99ff3a986.png)
![c](https://cloud.githubusercontent.com/assets/4093683/24473450/b163b0c0-149f-11e7-9640-5b1c416c3955.png)

Hope it was useful!
