### ISSUE TITLE
Xcode crashed

### ISSUE THREAD

**Issue by milankamilya** [shamasshahid/SSRadioButtonsController#7]
Xcode Version : 6.3
Whenever I am going build this project, Xcode stuck and on relaunch still same problem. 
I deleted the project from finder to come out this iteration.

**Comment by shamasshahid** [comment]
@milankamilya Are you talking about the sample project?

**Comment by milankamilya** [comment]
Yes

**Comment by shamasshahid** [comment]
@milankamilya Hi Milan, I haven't been able to reproduce this at my end. Please share some logs or some way to reproduce it.

**Comment by shamasshahid** [comment]
I am going to close this issue since I've been unable to reproduce it.
