### ISSUE TITLE
Title doesn't show on Radio buttons when i add button trough code.

### ISSUE THREAD

**Issue by Sahilberi** [shamasshahid/SSRadioButtonsController#9]
Hi ,
 when i add button from storyboard it works well but when i try to add through code it doesn't work fine . below is my code 

import UIKit

 class ViewController: UIViewController, SSRadioButtonControllerDelegate {

  var radioButtonController: SSRadioButtonsController?

  override func viewDidLoad() {
    super.viewDidLoad()

```
var buttonArray = [UIButton]()


let radioButton = SSRadioButton(frame: CGRect(x: 20, y: 20, width: 20, height: 20 ))
radioButton.circleRadius = 8
radioButton.setTitle("male", forState: .Normal)

let radioButton1 = SSRadioButton(frame: CGRect(x: 20, y: 60, width: 20, height: 20 ))
radioButton.circleRadius = 8
radioButton.setTitle("female", forState: .Normal)

self.view.addSubview(radioButton)
self.view.addSubview(radioButton1)

buttonArray.append(radioButton)
buttonArray.append(radioButton1)

radioButtonController = SSRadioButtonsController(buttons: buttonArray)
radioButtonController!.delegate = self
radioButtonController!.shouldLetDeSelect = true

// Do any additional setup after loading the view, typically from a nib.
```

  }

  func didSelectButton(aButton: UIButton?) {
    print(aButton)
  }

}

**Comment by shamasshahid** [comment]
There are 2 things wrong in your code. 
- Width for the button is too small to show the text as well. 
- Although you are using 2 button variable, but you still call `radioButton` instead of `radioButton1` after you create `radioButton1` 
- if `radioButtonController = SSRadioButtonsController(buttons: buttonArray)` is not working for you, try calling it by buttons, like `radioButtonController = SSRadioButtonsController(buttons: radioButton, radioButton1)`

**Comment by Sahilberi** [comment]
i changed width for button from 20  to 100 and changed call of radiobutton1. and i changed in your code
coz it was not allowing me to pass array. 
init(buttons: [UIButton]) {
        super.init()
        for aButton in buttons {
            aButton.addTarget(self, action: "pressed:", forControlEvents: UIControlEvents.TouchUpInside)
        }
        self.buttonsArray = buttons
    }
and it still now working.

**Comment by Sahilberi** [comment]
and as you were saying i tried that also but that is also no working
var buttonArray = [UIButton]()

```
let radioButton = SSRadioButton(frame: CGRect(x: 20, y: 20, width: 100, height: 20 ))
radioButton.circleRadius = 8

radioButton.setTitle("male", forState: .Normal)

let radioButton1 = SSRadioButton(frame: CGRect(x: 20, y: 60, width: 100, height: 20 ))
radioButton.circleRadius = 8
radioButton1.setTitle("female", forState: .Normal)

self.view.addSubview(radioButton)
self.view.addSubview(radioButton1)

buttonArray.append(radioButton)
buttonArray.append(radioButton1)

radioButtonController = SSRadioButtonsController(buttons: radioButton ,radioButton1)
radioButtonController!.delegate = self
radioButtonController!.shouldLetDeSelect = true
```

**Comment by shamasshahid** [comment]
Sorry, I forgot to tell you that you need to call `radioButton.setTitleColor(UIColor.blackColor(), forState: .Normal)`. Right now it's text is colored white. 
Also, you are still calling circleRadius on `radioButton` and not on `radioButton1`.

**Comment by Sahilberi** [comment]
ohh i didn't think about this . anyway thanks so much :)
